// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DataApi.proto
#ifndef GRPC_DataApi_2eproto__INCLUDED
#define GRPC_DataApi_2eproto__INCLUDED

#include "DataApi.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace DataApi {

class FileBrowser final {
 public:
  static constexpr char const* service_full_name() {
    return "DataApi.FileBrowser";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::DataApi::FileList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>> AsyncGetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>>(AsyncGetFileListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>> PrepareAsyncGetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>>(PrepareAsyncGetFileListRaw(context, request, cq));
    }
    virtual ::grpc::Status GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::DataApi::ImageInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>> AsyncGetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>>(AsyncGetFileInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>> PrepareAsyncGetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>>(PrepareAsyncGetFileInfoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>* AsyncGetFileListRaw(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::FileList>* PrepareAsyncGetFileListRaw(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>* AsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DataApi::ImageInfo>* PrepareAsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::DataApi::FileList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>> AsyncGetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>>(AsyncGetFileListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>> PrepareAsyncGetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>>(PrepareAsyncGetFileListRaw(context, request, cq));
    }
    ::grpc::Status GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::DataApi::ImageInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>> AsyncGetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>>(AsyncGetFileInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>> PrepareAsyncGetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>>(PrepareAsyncGetFileInfoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetFileList(::grpc::ClientContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetFileInfo(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>* AsyncGetFileListRaw(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DataApi::FileList>* PrepareAsyncGetFileListRaw(::grpc::ClientContext* context, const ::DataApi::FileListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>* AsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DataApi::ImageInfo>* PrepareAsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::DataApi::ImageInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetFileList_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFileInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetFileList(::grpc::ServerContext* context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response);
    virtual ::grpc::Status GetFileInfo(::grpc::ServerContext* context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFileList() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileList(::grpc::ServerContext* context, ::DataApi::FileListRequest* request, ::grpc::ServerAsyncResponseWriter< ::DataApi::FileList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFileInfo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileInfo(::grpc::ServerContext* context, ::DataApi::ImageInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::DataApi::ImageInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetFileList<WithAsyncMethod_GetFileInfo<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetFileList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::DataApi::FileListRequest, ::DataApi::FileList>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::DataApi::FileListRequest* request, ::DataApi::FileList* response) { return this->GetFileList(context, request, response); }));}
    void SetMessageAllocatorFor_GetFileList(
        ::grpc::experimental::MessageAllocator< ::DataApi::FileListRequest, ::DataApi::FileList>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::DataApi::FileListRequest, ::DataApi::FileList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetFileList(
      ::grpc::CallbackServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetFileList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetFileInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::DataApi::ImageInfoRequest, ::DataApi::ImageInfo>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::DataApi::ImageInfoRequest* request, ::DataApi::ImageInfo* response) { return this->GetFileInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetFileInfo(
        ::grpc::experimental::MessageAllocator< ::DataApi::ImageInfoRequest, ::DataApi::ImageInfo>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::DataApi::ImageInfoRequest, ::DataApi::ImageInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetFileInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetFileInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetFileList<ExperimentalWithCallbackMethod_GetFileInfo<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetFileList<ExperimentalWithCallbackMethod_GetFileInfo<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFileList() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFileInfo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFileList() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFileInfo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetFileList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFileList(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetFileList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetFileList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetFileInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFileInfo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetFileInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetFileInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFileList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFileList() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::DataApi::FileListRequest, ::DataApi::FileList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::DataApi::FileListRequest, ::DataApi::FileList>* streamer) {
                       return this->StreamedGetFileList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFileList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFileList(::grpc::ServerContext* /*context*/, const ::DataApi::FileListRequest* /*request*/, ::DataApi::FileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFileList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::DataApi::FileListRequest,::DataApi::FileList>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFileInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFileInfo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::DataApi::ImageInfoRequest, ::DataApi::ImageInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::DataApi::ImageInfoRequest, ::DataApi::ImageInfo>* streamer) {
                       return this->StreamedGetFileInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFileInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFileInfo(::grpc::ServerContext* /*context*/, const ::DataApi::ImageInfoRequest* /*request*/, ::DataApi::ImageInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFileInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::DataApi::ImageInfoRequest,::DataApi::ImageInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetFileList<WithStreamedUnaryMethod_GetFileInfo<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetFileList<WithStreamedUnaryMethod_GetFileInfo<Service > > StreamedService;
};

}  // namespace DataApi


#endif  // GRPC_DataApi_2eproto__INCLUDED
